In [8]:
import numpy as np
import cv2
import os

# 指定文件夹路径
folder_path = 'data'  # 替换成你的文件夹路径
mask_folder_path = 'result'  # 替换成你的掩码图像文件夹路径

# 获取文件夹中的所有文件
files = os.listdir(folder_path)

# 遍历每个文件
for file in files:
    # 检查文件是否是hdr文件
    if file.endswith('.hdr'):
        # 构建完整的hdr文件路径
        hdr_file_path = os.path.join(folder_path, file)

        # 读取hdr文件
        with open(hdr_file_path, 'r') as hdr_file:
            lines = hdr_file.readlines()
            for line in lines:
                if line.startswith('lines'):
                    height = int(line.split()[-1])
                elif line.startswith('samples'):
                    width = int(line.split()[-1])
                elif line.startswith('bands'):
                    bands = int(line.split()[-1])

        # 构建对应的raw文件路径
        raw_file_path = os.path.splitext(hdr_file_path)[0] + '.raw'

        # 读取raw光谱图像
        raw_image = np.fromfile(raw_file_path, dtype='float32')

        # 使用从hdr文件中读取的宽度、高度和波段数来重塑raw光谱图像的形状
        spectrum_image = raw_image.reshape((height, width, bands))

        # 构建对应的掩码图像路径
        mask_file_path = os.path.join(mask_folder_path, os.path.splitext(file)[0] + '.tiff')

        # 读取掩码图像，假设掩码图像是一个二值图像，西红柿的区域为255，其他区域为0
        mask = cv2.imread(mask_file_path, cv2.IMREAD_GRAYSCALE)

        # 创建一个和光谱图像形状相同的全零数组，用于存储西红柿区域的光谱图像
        tomato_spectrum_image = np.zeros_like(spectrum_image)

        # 将掩码图像扩展到和光谱图像形状相同，以便进行按位与操作
        mask = np.stack([mask]*bands, axis=2)

        # 使用掩码提取西红柿区域的光谱图像
        tomato_spectrum_image = np.where(mask == 255, spectrum_image, 0)

        # 计算每个谱段上西红柿的光谱信息均值
        average_values_tomato = np.mean(tomato_spectrum_image, axis=(0, 1))

        # 打印结果
        print(f"文件 {file} 中西红柿区域各波段的平均值:", average_values_tomato)

AxisError: axis 2 is out of bounds for array of dimension 1

In [2]:
import numpy as np
import cv2

# 指定raw光谱图像和mask掩码图像的路径
raw_file_path = 'data/39_ref.raw'  # 替换成你的raw光谱图像路径
mask_file_path = 'result/39.tiff'  # 替换成你的mask掩码图像路径

# 读取raw光谱图像
raw_image = np.fromfile(raw_file_path, dtype='float32')

# 使用图像的宽度、高度和波段数来重塑raw光谱图像的形状
height = 756 # 替换成你的图像高度
width = 1200  # 替换成你的图像宽度
bands = 224  # 替换成你的图像波段数
spectrum_image = raw_image.reshape((height, width, bands))

# 读取mask掩码图像，假设掩码图像是一个二值图像，西红柿的区域为255，其他区域为0
mask = cv2.imread(mask_file_path, cv2.IMREAD_GRAYSCALE)

# 创建一个和光谱图像形状相同的全零数组，用于存储西红柿区域的光谱图像
tomato_spectrum_image = np.zeros_like(spectrum_image)

# 将掩码图像扩展到和光谱图像形状相同，以便进行按位与操作
mask = np.stack([mask]*bands, axis=2)

# 使用掩码提取西红柿区域的光谱图像
tomato_spectrum_image = np.where(mask == 255, spectrum_image, 0)
print(tomato_spectrum_image)
# 计算每个谱段上西红柿的光谱信息均值
average_values_tomato = np.mean(tomato_spectrum_image, axis=(0, 1))

# 打印结果
print("西红柿区域各波段的平均值:", average_values_tomato)
import pandas as pd

# 创建一个DataFrame来存储结果
df = pd.DataFrame(average_values_tomato, columns=['Average Spectral Values'])

# # 将DataFrame导出为Excel文件
# df.to_excel('39.xlsx', index=False)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
西红柿区域各波段的平

In [10]:
import pandas as pd

# 创建一个DataFrame来存储结果
df = pd.DataFrame(average_values_tomato, columns=['Average Spectral Values'])

# 将DataFrame导出为Excel文件
df.to_excel('average_values_tomato.xlsx', index=False)