In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import numpy as np
import cv2 as cv
import os

In [4]:
##合成真彩色图像
#读取raw文件
imagePath ='data/new/yellow/1.raw' 
print(type(imagePath))
rawImage = np.fromfile(imagePath,"uint16")
print(type(rawImage))
rawShape = rawImage.shape
print(rawShape)
formatImage = np.zeros((87,2048,224))
for row in range(0,87):
    for dim in range(0,224):
        formatImage[row,:,dim] = rawImage[(dim + row*224) * 2048:(dim + 1 + row*224)* 2048]
print(formatImage.shape)
print(type(formatImage))
print(formatImage)

#选择通道数为12/46/96的三个通道相当于rgb三通道的图片
# imgR = formatImage[:,:,88]
# imgG = formatImage[:,:,58]
# imgB = formatImage[:,:,31]
#  
# rgbImg = cv.merge([imgR,imgG,imgB])
# print(rgbImg.shape)
# print(type(rgbImg))
# cv.imshow('test',rgbImg)
# cv.waitKey(0)
# cv.destroyAllWindows()
# plt.imshow(rgbImg)
# #保存
# plt.savefig('result/1_ref.png')



<class 'str'>
<class 'numpy.ndarray'>
(39911424,)
(87, 2048, 224)
<class 'numpy.ndarray'>
[[[1686. 1654. 1654. ... 1654. 1622. 1654.]
  [1689. 1673. 1673. ... 1689. 1689. 1673.]
  [1673. 1657. 1657. ... 1673. 1753. 1609.]
  ...
  [1609. 1689. 1721. ... 1657. 1705. 1577.]
  [1718. 1702. 1654. ... 1574. 1638. 1686.]
  [1686. 1670. 1686. ... 1590. 1686. 1670.]]

 [[1654. 1670. 1718. ... 1686. 1654. 1734.]
  [1721. 1657. 1641. ... 1689. 1657. 1721.]
  [1641. 1625. 1705. ... 1705. 1689. 1609.]
  ...
  [1625. 1673. 1689. ... 1673. 1673. 1641.]
  [1686. 1622. 1654. ... 1686. 1654. 1606.]
  [1734. 1654. 1670. ... 1510. 1654. 1654.]]

 [[1718. 1702. 1670. ... 1622. 1670. 1686.]
  [1657. 1641. 1641. ... 1705. 1689. 1657.]
  [1673. 1673. 1689. ... 1673. 1625. 1657.]
  ...
  [1625. 1673. 1705. ... 1625. 1609. 1625.]
  [1702. 1686. 1654. ... 1638. 1670. 1654.]
  [1638. 1702. 1686. ... 1670. 1702. 1638.]]

 ...

 [[1638. 1606. 1686. ... 1654. 1670. 1638.]
  [1721. 1673. 1673. ... 1689. 1641. 1625.]


In [5]:
##合成真彩色图像
#读取raw文件
imagePath = 'data/数据/原光源（条光）/黄果（成熟）/1.raw'  
print(type(imagePath))
rawImage = np.fromfile(imagePath,"float16")
print(type(rawImage))
rawShape = rawImage.shape
print(rawShape)
formatImage = np.zeros((110,2048,224))
# 假设 rawImage 已经正确读取
raw_length = len(rawImage)  # 获取 rawImage 的实际长度

for row in range(0, 110):
    for dim in range(0, 224):
        start_index = (dim + row*224) * 2048
        end_index = (dim + 1 + row*224) * 2048
        
        # 检查索引是否在 rawImage 的边界内
        if start_index < raw_length and end_index <= raw_length:
            formatImage[row,:,dim] = rawImage[start_index:end_index]
        else:
            print(f"索引超出范围: 行 {row}, 波段 {dim}")

# for row in range(0,110):
#     for dim in range(0,224):
#         # formatImage[row,:,dim] = rawImage[(dim + row*224) * 2048:(dim + 1 + row*224)* 2048]
    
#选择通道数为12/46/96的三个通道相当于rgb三通道的图片
# imgR = formatImage[:,:,31]
# imgG = formatImage[:,:,58]
# imgB = formatImage[:,:,88]
#  
# rgbImg = cv.merge([imgR,imgG,imgB])
# print(rgbImg.shape)
# print(type(rgbImg))
# cv.imshow('test',rgbImg)
# cv.waitKey(0)
# cv.destroyAllWindows()
# plt.imshow(rgbImg)
# #保存
# plt.savefig('result/1_ref.png')

<class 'str'>
<class 'numpy.ndarray'>
(50462720,)


In [5]:
##循环合成真彩色图像
# 指定文件夹路径
folder_path = 'data'  # 替换成你的文件夹路径
# mask_out_path = 'result'  # 替换成你的掩码图像文件夹路径

# 获取文件夹中的所有文件
files = os.listdir(folder_path)


for i in range(1, 40):
    with open(folder_path + '/' + str(i) + '_ref.hdr', 'r') as hdr_file:
        lines = hdr_file.readlines()
        for line in lines:
            if line.startswith('lines'):
                height = int(line.split()[-1])
            elif line.startswith('samples'):
                width = int(line.split()[-1])
            elif line.startswith('bands'):
                bands = int(line.split()[-1])
    raw_image = np.fromfile(folder_path + '/' + str(i) + '_ref.raw', dtype='float32')
    
    formatImage = np.zeros((height, width, bands))
    for row in range(0, height):
        for dim in range(0, bands):
            formatImage[row,:,dim] = raw_image[(dim + row*bands) * width:(dim + 1 + row*bands)* width]
    #选择通道数为12/46/96的三个通道相当于rgb三通道的图片
    imgR = formatImage[:,:,12]
    imgG = formatImage[:,:,46]
    imgB = formatImage[:,:,96]
    
    rgbImg = cv.merge([imgR,imgG,imgB])
    print(rgbImg.shape)
    print(type(rgbImg))
    
    Img_Name = "./tcimage/" + str(i)+ ".png"
    cv.imwrite(Img_Name, rgbImg*255)
    # cv.imshow('test',rgbImg)
    # cv.waitKey(0)
    # cv.destroyAllWindows()
# #读取raw文件
# imagePath = 'data/1_ref.raw'  
# print(type(imagePath))
# rawImage = np.fromfile(imagePath,"float32")
# print(type(rawImage))
# rawShape = rawImage.shape
# print(rawShape)
# formatImage = np.zeros((928,1200,224))
# for row in range(0,928):
#     for dim in range(0,224):
#         formatImage[row,:,dim] = rawImage[(dim + row*224) * 1200:(dim + 1 + row*224)* 1200]
# #选择通道数为12/46/96的三个通道相当于rgb三通道的图片
# imgR = formatImage[:,:,12]
# imgG = formatImage[:,:,46]
# imgB = formatImage[:,:,96]
 
# rgbImg = cv.merge([imgR,imgG,imgB])
# print(rgbImg.shape)
# print(type(rgbImg))
#     cv.imshow('test',rgbImg)
#     cv.waitKey(0)
#     cv.destroyAllWindows()
# plt.imshow(rgbImg)
# #保存
# plt.savefig('result/1_ref.png')



(928, 1200, 3)
<class 'numpy.ndarray'>
(848, 1200, 3)
<class 'numpy.ndarray'>
(902, 1200, 3)
<class 'numpy.ndarray'>
(795, 1200, 3)
<class 'numpy.ndarray'>
(783, 1200, 3)
<class 'numpy.ndarray'>
(708, 1200, 3)
<class 'numpy.ndarray'>
(747, 1200, 3)
<class 'numpy.ndarray'>
(630, 1200, 3)
<class 'numpy.ndarray'>
(709, 1200, 3)
<class 'numpy.ndarray'>
(699, 1200, 3)
<class 'numpy.ndarray'>
(796, 1200, 3)
<class 'numpy.ndarray'>
(865, 1200, 3)
<class 'numpy.ndarray'>
(791, 1200, 3)
<class 'numpy.ndarray'>
(723, 1200, 3)
<class 'numpy.ndarray'>
(797, 1200, 3)
<class 'numpy.ndarray'>
(760, 1200, 3)
<class 'numpy.ndarray'>
(701, 1200, 3)
<class 'numpy.ndarray'>
(770, 1200, 3)
<class 'numpy.ndarray'>
(637, 1200, 3)
<class 'numpy.ndarray'>
(729, 1200, 3)
<class 'numpy.ndarray'>
(762, 1200, 3)
<class 'numpy.ndarray'>
(732, 1200, 3)
<class 'numpy.ndarray'>
(839, 1200, 3)
<class 'numpy.ndarray'>
(760, 1200, 3)
<class 'numpy.ndarray'>
(711, 1200, 3)
<class 'numpy.ndarray'>
(736, 1200, 3)
<class 'nu